/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DespreRouteImport } from './routes/despre'
import { Route as SurseRouteImport } from './routes/surse'
import { Route as StiriSlugRouteImport } from './routes/stiri/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreRoute = DespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => rootRouteImport,
} as any)
const SurseRoute = SurseRouteImport.update({
  id: '/surse',
  path: '/surse',
  getParentRoute: () => rootRouteImport,
} as any)
const StiriSlugRoute = StiriSlugRouteImport.update({
  id: '/stiri/$slug',
  path: '/stiri/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/despre': typeof DespreRoute
  '/surse': typeof SurseRoute
  '/stiri/$slug': typeof StiriSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/despre': typeof DespreRoute
  '/surse': typeof SurseRoute
  '/stiri/$slug': typeof StiriSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/despre': typeof DespreRoute
  '/surse': typeof SurseRoute
  '/stiri/$slug': typeof StiriSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/despre' | '/surse' | '/stiri/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/despre' | '/surse' | '/stiri/$slug'
  id: '__root__' | '/' | '/despre' | '/surse' | '/stiri/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DespreRoute: typeof DespreRoute
  SurseRoute: typeof SurseRoute
  StiriSlugRoute: typeof StiriSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre': {
      id: '/despre'
      path: '/despre'
      fullPath: '/despre'
      preLoaderRoute: typeof DespreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surse': {
      id: '/surse'
      path: '/surse'
      fullPath: '/surse'
      preLoaderRoute: typeof SurseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stiri/$slug': {
      id: '/stiri/$slug'
      path: '/stiri/$slug'
      fullPath: '/stiri/$slug'
      preLoaderRoute: typeof StiriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DespreRoute: DespreRoute,
  SurseRoute: SurseRoute,
  StiriSlugRoute: StiriSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
